// Bootstrapped from MySQL "homedb" on 2026-06-22T00:57:28.274Z
// 已移除 admin（merge 后废弃）和 sessions（express-mysql-session 管理）。
// 共 20 张表。添加新表/列后运行 node prisma/diff.js --apply 同步到 MySQL。

module.exports = {
  "activations": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "user_name": "varchar(255) NOT NULL",
    "organization": "varchar(255)",
    "email": "varchar(255) NOT NULL",
    "software_name": "varchar(255) NOT NULL",
    "mac_address": "varchar(255)",
    "install_date": "varchar(100)",
    "activate_date": "varchar(100)",
    "expire_date": "varchar(100)",
    "activation_key": "varchar(255)",
    "status": "varchar(50) DEFAULT 'active'",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "activation_logs": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "mac_address": "varchar(255)",
    "software_name": "varchar(255)",
    "activation_key": "varchar(255)",
    "status": "varchar(50)",
    "ip": "varchar(100)",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "device_software_expire": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "software_name": "varchar(255) NOT NULL",
    "software_short_name": "varchar(100)",
    "mac_address": "varchar(255) NOT NULL",
    "is_installed": "tinyint(1) DEFAULT 0",
    "is_activated": "tinyint(1) DEFAULT 0",
    "install_date": "timestamp",
    "register_date": "timestamp",
    "activate_date": "timestamp",
    "last_activate_date": "timestamp",
    "activation_duration": "int(11) DEFAULT 0",
    "expire_date": "varchar(100) NOT NULL",
    "activation_key": "varchar(255)",
    "user_email": "varchar(255)",
    "user_name": "varchar(255)",
    "organization": "varchar(255)",
    "status": "varchar(50) DEFAULT 'active'",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "updated_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "last_heartbeat_at": "timestamp"
  },
  "faqs": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "question": "varchar(500) NOT NULL",
    "answer": "text NOT NULL",
    "sort_order": "int(11) DEFAULT 0",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "updated_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "installations": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "software_name": "varchar(255) NOT NULL",
    "software_version": "varchar(100)",
    "user_name": "varchar(255) NOT NULL",
    "user_email": "varchar(255) NOT NULL",
    "organization": "varchar(255)",
    "mac_address": "varchar(255)",
    "install_date": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "expire_date": "varchar(100)",
    "status": "varchar(50) DEFAULT 'active'",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "software_short_name": "varchar(100)"
  },
  "login_logs": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "username": "varchar(255)",
    "ip": "varchar(100)",
    "user_agent": "text",
    "status": "varchar(50)",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "operation_logs": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "username": "varchar(255)",
    "action": "varchar(255)",
    "target": "varchar(500)",
    "details": "text",
    "ip": "varchar(100)",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "orders": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "user_id": "int(11)",
    "total_amount": "double",
    "status": "varchar(50) DEFAULT 'pending'",
    "verification_code": "varchar(255)",
    "order_number": "varchar(100)",
    "is_archived": "int(11) DEFAULT 0",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "paid_at": "timestamp",
    "payment_method": "varchar(50)",
    "paypal_order_id": "varchar(255)"
  },
  "order_items": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "order_id": "int(11) NOT NULL",
    "product_id": "int(11) NOT NULL",
    "product_name": "varchar(255) NOT NULL",
    "product_short_name": "varchar(100) NOT NULL",
    "price": "double NOT NULL",
    "quantity": "int(11) DEFAULT 1",
    "duration_days": "int(11) NOT NULL"
  },
  "order_item_codes": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "order_item_id": "int(11) NOT NULL",
    "code": "varchar(64) NOT NULL UNIQUE",
    "is_activated": "int(11) DEFAULT 0",
    "activated_at": "timestamp",
    "activated_by_user": "varchar(255)",
    "activated_by_mac": "varchar(64)"
  },
  "products": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "name": "varchar(255) NOT NULL",
    "category": "varchar(255)",
    "price": "double NOT NULL",
    "pricing_tiers": "text",
    "description": "text",
    "version": "varchar(100)",
    "platform": "varchar(100)",
    "features": "text",
    "icon": "varchar(500)",
    "featured": "int(11) DEFAULT 0",
    "download_url": "varchar(500)",
    "external_link": "int(11) DEFAULT 0",
    "detail_page": "varchar(500)",
    "image": "varchar(500)",
    "image_dark_bg": "int(11) DEFAULT 0",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "updated_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "short_name": "varchar(100) NOT NULL DEFAULT '' UNIQUE",
    "status": "tinyint(1) NOT NULL DEFAULT 1",
    "is_course": "int(11) DEFAULT 0"
  },
  "product_links": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "product_id": "int(11) NOT NULL",
    "platform": "varchar(50) NOT NULL",
    "url": "varchar(500) NOT NULL",
    "sort_order": "int(11) DEFAULT 0",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "product_docs": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "product_id": "int(11) NOT NULL",
    "title": "varchar(255) NOT NULL",
    "slug": "varchar(255) NOT NULL",
    "content_html": "mediumtext NOT NULL",
    "excerpt": "varchar(500)",
    "sort_order": "int(11) DEFAULT 0",
    "status": "enum('draft','published') DEFAULT 'draft'",
    "author_username": "varchar(255)",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "updated_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "published_at": "timestamp"
  },
  "registration_logs": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "email": "varchar(255)",
    "ip": "varchar(100)",
    "user_agent": "text",
    "status": "varchar(50)",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "settings": {
    "id": "int(11) NOT NULL DEFAULT 1 PRIMARY KEY",
    "company_name": "varchar(255)",
    "logo": "varchar(500)",
    "description": "text",
    "banners": "text",
    "ssl_domain": "varchar(255)",
    "ssl_cert_path": "varchar(500)",
    "ssl_key_path": "varchar(500)",
    "ssl_ca_path": "varchar(500)",
    "http_port": "int(11) DEFAULT 10000",
    "https_port": "int(11) DEFAULT 10001",
    "smtp_host": "varchar(255)",
    "smtp_port": "int(11) DEFAULT 587",
    "smtp_user": "varchar(255)",
    "smtp_password": "varchar(255)",
    "smtp_from": "varchar(255)",
    "smtp_secure": "int(11) DEFAULT 0",
    "wechat_id": "varchar(255)",
    "admin_email": "varchar(255)",
    "ai_config": "text",
    "carddav_config": "text",
    "site_theme": "varchar(50) DEFAULT 'minimal'",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "updated_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "subscribers": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "email": "varchar(255) NOT NULL UNIQUE",
    "subscribed": "int(11) DEFAULT 1",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "support_tickets": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "subject": "varchar(500) NOT NULL",
    "description": "text NOT NULL",
    "user_name": "varchar(255) NOT NULL",
    "user_email": "varchar(255) NOT NULL",
    "user_phone": "varchar(50)",
    "status": "varchar(50) DEFAULT 'open'",
    "priority": "varchar(50) DEFAULT 'normal'",
    "replies": "text",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "updated_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "system_settings": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "setting_key": "varchar(100) NOT NULL UNIQUE",
    "setting_value": "text",
    "description": "varchar(500)",
    "updated_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "updated_by": "varchar(100)"
  },
  "telemetry": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "device_id": "varchar(255) NOT NULL",
    "app_name": "varchar(255) NOT NULL",
    "app_version": "varchar(100)",
    "first_seen": "timestamp",
    "events": "text",
    "platform": "varchar(100)",
    "os_version": "varchar(100)",
    "client_ip": "varchar(100)",
    "user_agent": "text",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  },
  "users": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "username": "varchar(255) NOT NULL UNIQUE",
    "password": "varchar(255) NOT NULL",
    "email": "varchar(255)",
    "phone": "varchar(50)",
    "real_name": "varchar(255)",
    "company_name": "varchar(255)",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "is_admin": "tinyint(1) NOT NULL DEFAULT 0",
    "email_verified": "int(11) DEFAULT 0",
    "email_verify_token": "varchar(128)",
    "email_verify_expires_at": "timestamp"
  },
  "user_software_status": {
    "id": "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY",
    "user_name": "varchar(255) NOT NULL",
    "software_short_name": "varchar(100) NOT NULL",
    "first_run": "timestamp",
    "last_activated_at": "timestamp",
    "duration": "int(11) DEFAULT 0",
    "expire_date": "timestamp",
    "lock": "int(11) DEFAULT 0",
    "last_reminder_at": "timestamp",
    "reminder_count": "int(11) DEFAULT 0",
    "created_at": "timestamp DEFAULT CURRENT_TIMESTAMP",
    "updated_at": "timestamp DEFAULT CURRENT_TIMESTAMP"
  }
};
